-- MindUp detailed, tab-based staff permissions.
-- Run after "SQL staff granular permissions.sql". Idempotent.

ALTER TABLE public.app_permissions
  ADD COLUMN IF NOT EXISTS group_key text,
  ADD COLUMN IF NOT EXISTS group_label text,
  ADD COLUMN IF NOT EXISTS access_level text NOT NULL DEFAULT 'basic',
  ADD COLUMN IF NOT EXISTS is_sensitive boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_assignable boolean NOT NULL DEFAULT true;

ALTER TABLE public.app_permissions DROP CONSTRAINT IF EXISTS app_permissions_access_level_check;
ALTER TABLE public.app_permissions
  ADD CONSTRAINT app_permissions_access_level_check
  CHECK (access_level IN ('view', 'basic', 'full'));

CREATE TABLE IF NOT EXISTS public.permission_change_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  permission_key text NOT NULL,
  previous_value boolean,
  new_value boolean,
  changed_by uuid REFERENCES public.users(id) ON DELETE SET NULL,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS permission_change_log_target_idx
  ON public.permission_change_log(target_user_id, changed_at DESC);

-- group_key is also the menu/page permission key. This lets the admin UI render
-- one accordion per menu tab and makes presets deterministic.
INSERT INTO public.app_permissions
  (permission_key, section, label, description, sort_order, group_key, group_label, access_level, is_sensitive, is_assignable)
VALUES
  ('page.ops_center','Bảng điều hành','Truy cập Bảng điều hành','Mở tab Bảng điều hành.',10,'page.ops_center','Bảng điều hành','view',false,true),
  ('ops.financial.view','Bảng điều hành','Xem số liệu tài chính','Xem tổng thu, chi và các chỉ số tài chính toàn trung tâm.',11,'page.ops_center','Bảng điều hành','full',true,true),

  ('page.home','Trang chủ','Truy cập Trang chủ','Mở trang chủ.',20,'page.home','Trang chủ','view',false,true),

  ('page.courses','Khóa học','Truy cập Khóa học','Xem danh sách và nội dung khóa học.',30,'page.courses','Khóa học','view',false,true),
  ('courses.manage','Khóa học','Tạo và sửa khóa học','Tạo khóa học, sửa nội dung và lịch học.',31,'page.courses','Khóa học','basic',false,true),
  ('courses.enrollments.manage','Khóa học','Quản lý học viên khóa học','Thêm, duyệt hoặc loại học viên khỏi khóa học.',32,'page.courses','Khóa học','full',true,true),
  ('courses.delete','Khóa học','Xóa khóa học','Xóa khóa học và dữ liệu liên quan.',33,'page.courses','Khóa học','full',true,true),
  ('courses.results.view','Khóa học','Xem kết quả toàn khóa','Xem kết quả học tập của mọi học viên trong khóa.',34,'page.courses','Khóa học','full',true,true),

  ('page.classes','Lớp học','Truy cập Lớp học','Xem lớp học được phép truy cập.',40,'page.classes','Lớp học','view',false,true),
  ('class.attendance','Lớp học','Điểm danh','Điểm danh học sinh trong lớp phụ trách.',41,'page.classes','Lớp học','basic',false,true),
  ('class.sessions.manage','Lớp học','Quản lý buổi học','Tạo, sửa và hủy buổi học.',42,'page.classes','Lớp học','basic',false,true),
  ('class.evaluations.manage','Lớp học','Nhận xét buổi học','Nhập và sửa nhận xét học tập.',43,'page.classes','Lớp học','basic',false,true),
  ('class.students.manage','Lớp học','Quản lý học sinh trong lớp','Thêm, chuyển hoặc xóa học sinh khỏi lớp.',44,'page.classes','Lớp học','full',true,true),
  ('classes.manage','Lớp học','Tạo và sửa lớp học','Tạo lớp, sửa cấu hình và phân công nhân sự.',45,'page.classes','Lớp học','full',true,true),
  ('classes.delete','Lớp học','Xóa lớp học','Xóa lớp học và dữ liệu liên quan.',46,'page.classes','Lớp học','full',true,true),

  ('page.tasks','Công việc','Truy cập Công việc','Xem công việc được giao.',50,'page.tasks','Công việc','view',false,true),
  ('tasks.self_update','Công việc','Cập nhật công việc của mình','Cập nhật tiến độ và nộp kết quả công việc được giao.',51,'page.tasks','Công việc','basic',false,true),
  ('tasks.manage','Công việc','Tạo và giao công việc','Tạo, phân công và chỉnh sửa công việc của nhân viên.',52,'page.tasks','Công việc','full',true,true),
  ('tasks.templates.manage','Công việc','Quản lý mẫu công việc','Tạo, sửa và xóa mẫu công việc.',53,'page.tasks','Công việc','full',true,true),
  ('tasks.staff_overview','Công việc','Xem tổng quan nhân viên','Xem tiến độ và nhật ký công việc của toàn bộ nhân viên.',54,'page.tasks','Công việc','full',true,true),

  ('page.teacher_schedule','Giáo viên và TKB','Truy cập Giáo viên và TKB','Xem giáo viên và thời khóa biểu.',60,'page.teacher_schedule','Giáo viên và TKB','view',false,true),
  ('teacher_schedule.manage','Giáo viên và TKB','Quản lý thời khóa biểu','Dành cho chức năng chỉnh lịch và phân công khi được bổ sung.',61,'page.teacher_schedule','Giáo viên và TKB','full',true,false),

  ('page.personal_schedule','Lịch học cá nhân','Truy cập Lịch học cá nhân','Xem lịch học của bản thân hoặc con.',70,'page.personal_schedule','Lịch học cá nhân','view',false,true),

  ('page.public_exam','Đề thi','Truy cập Đề thi','Xem và làm các đề thi được phép.',80,'page.public_exam','Đề thi','view',false,true),
  ('public_exam.manage','Đề thi','Quản lý đề thi công khai','Tạo, sửa, ẩn và phát hành đề thi.',81,'page.public_exam','Đề thi','basic',false,true),
  ('public_exam.results.manage','Đề thi','Quản lý kết quả thi','Xem toàn bộ kết quả và xử lý bài làm.',82,'page.public_exam','Đề thi','full',true,true),

  ('page.game','Game','Truy cập Game','Mở khu vực trò chơi học tập.',90,'page.game','Game','view',false,true),
  ('game.manage','Game','Quản lý nội dung Game','Tạo và sửa cấu hình trò chơi.',91,'page.game','Game','basic',false,true),
  ('game.competition.manage','Game','Quản lý đấu trường','Tạo, sửa và xóa các cuộc thi/đấu trường.',92,'page.game','Game','full',true,true),

  ('page.tuition','Học phí','Truy cập Học phí','Mở tab Học phí.',100,'page.tuition','Học phí','view',false,true),
  ('tuition.view_assigned','Học phí','Xem học phí lớp phụ trách','Xem học phí và liên hệ phụ huynh của lớp được phân công.',101,'page.tuition','Học phí','view',true,true),
  ('tuition.view_all','Học phí','Xem toàn bộ học phí','Xem học phí và liên hệ phụ huynh toàn trung tâm.',102,'page.tuition','Học phí','full',true,true),
  ('tuition.collect','Học phí','Thu tiền thủ công','Ghi nhận khoản học phí đã thu.',103,'page.tuition','Học phí','basic',true,true),
  ('tuition.notes.manage','Học phí','Sửa ghi chú học phí','Thêm và sửa ghi chú cho từng học sinh.',104,'page.tuition','Học phí','basic',false,true),
  ('tuition.notify','Học phí','Gửi thông báo học phí','Gửi thông báo học phí trên web/app.',105,'page.tuition','Học phí','basic',true,true),
  ('tuition.invoice','Học phí','In hóa đơn','Tạo và in hóa đơn học phí.',106,'page.tuition','Học phí','basic',false,true),
  ('tuition.export','Học phí','Xuất dữ liệu học phí','Dành cho chức năng xuất báo cáo học phí khi được bổ sung.',107,'page.tuition','Học phí','basic',true,false),
  ('tuition.zalo_queue.manage','Học phí','Quản lý gửi Zalo','Xếp hàng, hủy và gửi lại thông báo học phí qua Zalo.',108,'page.tuition','Học phí','full',true,true),
  ('tuition.transactions.view','Học phí','Xem giao dịch chưa khớp','Xem nội dung và số tiền giao dịch ngân hàng chưa khớp.',109,'page.tuition','Học phí','full',true,true),
  ('tuition.transactions.manage','Học phí','Xử lý giao dịch chưa khớp','Đánh dấu đã xử lý hoặc xóa giao dịch chưa khớp.',110,'page.tuition','Học phí','full',true,true),
  ('tuition.surplus.manage','Học phí','Chuyển tiền nộp dư','Chuyển tiền nộp dư sang kỳ tiếp theo.',111,'page.tuition','Học phí','full',true,true),
  ('tuition.refund','Học phí','Hoàn tiền','Giảm số tiền đã thu và ghi nhận hoàn tiền.',112,'page.tuition','Học phí','full',true,true),
  ('tuition.lock','Học phí','Chốt hoặc mở học phí','Khóa hoặc mở dữ liệu học phí của tháng.',113,'page.tuition','Học phí','full',true,true),

  ('page.income','Thu nhập và thu chi','Truy cập Thu nhập','Mở tab Thu nhập và thu chi.',120,'page.income','Thu nhập và thu chi','view',false,true),
  ('income.self.view','Thu nhập và thu chi','Xem thu nhập của mình','Xem tiền lương và thu nhập cá nhân.',121,'page.income','Thu nhập và thu chi','view',true,true),
  ('income.all.view','Thu nhập và thu chi','Xem toàn bộ thu chi','Xem số liệu thu chi và thu nhập toàn trung tâm.',122,'page.income','Thu nhập và thu chi','full',true,true),
  ('income.manage','Thu nhập và thu chi','Quản lý sổ thu chi','Bổ sung mô tả và đối chiếu giao dịch.',123,'page.income','Thu nhập và thu chi','full',true,true),
  ('income.payroll.manage','Thu nhập và thu chi','Quản lý lương','Tính, điều chỉnh và chốt lương nhân viên.',124,'page.income','Thu nhập và thu chi','full',true,true),
  ('income.export','Thu nhập và thu chi','Xuất báo cáo thu chi','Dành cho chức năng xuất báo cáo thu chi khi được bổ sung.',125,'page.income','Thu nhập và thu chi','basic',true,false),

  ('page.resources','Tài liệu tham khảo','Truy cập Tài liệu','Xem tài liệu tham khảo.',130,'page.resources','Tài liệu tham khảo','view',false,true),
  ('resources.manage','Tài liệu tham khảo','Quản lý tài liệu','Tạo, sửa và xóa tài liệu.',131,'page.resources','Tài liệu tham khảo','basic',false,true),

  ('page.question_bank','Ngân hàng câu hỏi','Truy cập Ngân hàng câu hỏi','Xem câu hỏi được phép.',140,'page.question_bank','Ngân hàng câu hỏi','view',false,true),
  ('question.manage','Ngân hàng câu hỏi','Tạo và sửa câu hỏi','Tạo, sửa, ẩn và tổ chức câu hỏi.',141,'page.question_bank','Ngân hàng câu hỏi','basic',false,true),
  ('question.import','Ngân hàng câu hỏi','Nhập câu hỏi hàng loạt','Nhập câu hỏi từ Word hoặc nguồn dữ liệu khác.',142,'page.question_bank','Ngân hàng câu hỏi','basic',false,true),
  ('question.delete_permanent','Ngân hàng câu hỏi','Xóa vĩnh viễn câu hỏi','Xóa vĩnh viễn câu hỏi khỏi hệ thống.',143,'page.question_bank','Ngân hàng câu hỏi','full',true,true),

  ('page.exam_editor','Đề kiểm tra','Truy cập Đề kiểm tra','Mở công cụ soạn và quản lý đề.',150,'page.exam_editor','Đề kiểm tra','view',false,true),
  ('exam.manage','Đề kiểm tra','Tạo và sửa đề','Tạo, sửa và xóa đề do mình quản lý.',151,'page.exam_editor','Đề kiểm tra','basic',false,true),
  ('exam.results.manage','Đề kiểm tra','Quản lý mọi kết quả','Dành cho màn hình quản lý kết quả tập trung khi được bổ sung.',152,'page.exam_editor','Đề kiểm tra','full',true,false),

  ('page.trial_requests','Đăng ký học thử','Truy cập Đăng ký học thử','Xem danh sách đăng ký học thử.',160,'page.trial_requests','Đăng ký học thử','view',false,true),
  ('trial.manage','Đăng ký học thử','Xử lý đăng ký học thử','Cập nhật, phân lớp và liên hệ đăng ký học thử.',161,'page.trial_requests','Đăng ký học thử','basic',true,true),

  ('page.push_debug','Kiểm tra thông báo','Truy cập Kiểm tra thông báo','Mở công cụ kiểm tra thông báo.',170,'page.push_debug','Kiểm tra thông báo','full',true,true),

  ('page.system','Hệ thống','Truy cập Hệ thống','Mở tab quản trị hệ thống.',180,'page.system','Hệ thống','view',true,true),
  ('system.catalogs.manage','Hệ thống','Quản lý danh mục','Quản lý phòng, khối, môn và chủ đề.',181,'page.system','Hệ thống','basic',true,true),
  ('system.students.manage','Hệ thống','Quản lý học sinh','Xem và cập nhật dữ liệu học sinh/phụ huynh.',182,'page.system','Hệ thống','basic',true,true),
  ('system.staff.manage','Hệ thống','Quản lý nhân viên','Tạo và cập nhật giáo viên/trợ giảng.',183,'page.system','Hệ thống','full',true,true),
  ('system.templates.manage','Hệ thống','Quản lý mẫu nội dung','Quản lý mẫu nhận xét và tin nhắn tự động.',184,'page.system','Hệ thống','basic',true,true),
  ('system.logs.view','Hệ thống','Xem nhật ký vận hành','Xem nhật ký hoạt động của hệ thống.',185,'page.system','Hệ thống','view',true,true),
  ('system.zalo.manage','Hệ thống','Quản lý kết nối Zalo','Chạy kiểm tra, kết nối và đồng bộ Zalo phụ huynh.',186,'page.system','Hệ thống','full',true,true),
  ('system.appearance.manage','Hệ thống','Quản lý giao diện','Thay đổi giao diện toàn hệ thống.',187,'page.system','Hệ thống','full',true,true),
  ('system.permissions.manage','Hệ thống','Phân quyền nhân viên','Thay đổi quyền của từng nhân viên.',188,'page.system','Hệ thống','full',true,true),

  ('page.facebook','Đăng bài Facebook','Truy cập Đăng bài Facebook','Mở lịch và công cụ đăng bài Facebook.',190,'page.facebook','Đăng bài Facebook','view',false,true),
  ('facebook.generate','Đăng bài Facebook','Tạo nội dung bằng AI','Tạo nội dung và hình ảnh bằng AI.',191,'page.facebook','Đăng bài Facebook','basic',true,true),
  ('facebook.manage','Đăng bài Facebook','Soạn và lưu bản nháp','Tạo, sửa và xóa bản nháp bài đăng.',192,'page.facebook','Đăng bài Facebook','basic',false,true),
  ('facebook.schedule','Đăng bài Facebook','Hẹn lịch Facebook','Tạo hoặc cập nhật lịch đăng Facebook.',193,'page.facebook','Đăng bài Facebook','full',true,true),
  ('facebook.publish','Đăng bài Facebook','Đăng bài ngay','Dành cho nút đăng ngay khi được bật trên giao diện.',194,'page.facebook','Đăng bài Facebook','full',true,false),
  ('facebook.config.manage','Đăng bài Facebook','Quản lý fanpage và lịch mẫu','Thay đổi cấu hình fanpage, loại bài và lịch mẫu.',195,'page.facebook','Đăng bài Facebook','full',true,true)
ON CONFLICT (permission_key) DO UPDATE SET
  section = EXCLUDED.section,
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  group_key = EXCLUDED.group_key,
  group_label = EXCLUDED.group_label,
  access_level = EXCLUDED.access_level,
  is_sensitive = EXCLUDED.is_sensitive,
  is_assignable = EXCLUDED.is_assignable;

-- Keep the old broad tuition permission for compatibility, but do not display it.
UPDATE public.app_permissions
SET is_assignable = false, group_key = 'page.tuition', group_label = 'Học phí'
WHERE permission_key = 'tuition.manage';

-- Permission administration remains an admin-only root capability. Showing it as
-- assignable would let the UI promise a delegation that the protected RPC rejects.
UPDATE public.app_permissions
SET is_assignable = false
WHERE permission_key = 'system.permissions.manage';

-- Defaults preserve current role behaviour. Admin remains all-powerful through mindup_is_admin.
INSERT INTO public.role_permission_defaults(role_name, permission_key, allowed)
SELECT role_name, permission_key, true
FROM (VALUES
  ('teacher','tasks.self_update'), ('teacher','class.evaluations.manage'),
  ('teacher','class.students.manage'), ('teacher','public_exam.manage'),
  ('teacher','courses.results.view'),
  ('teacher','income.self.view'), ('teacher','resources.manage'), ('teacher','question.import'),
  ('teacher','facebook.generate'), ('teacher','facebook.schedule'), ('teacher','facebook.publish'),

  ('assistant','tasks.self_update'), ('assistant','class.evaluations.manage'),
  ('assistant','question.import'), ('assistant','facebook.generate'),
  ('assistant','facebook.schedule'), ('assistant','facebook.publish')
) AS defaults(role_name, permission_key)
ON CONFLICT (role_name, permission_key) DO UPDATE SET allowed = EXCLUDED.allowed;

-- Existing broad permissions map to the detailed actions that represented their old behaviour.
INSERT INTO public.role_permission_defaults(role_name, permission_key, allowed)
SELECT 'admin', permission_key, true
FROM public.app_permissions
ON CONFLICT (role_name, permission_key) DO UPDATE SET allowed = true;

CREATE OR REPLACE FUNCTION public.admin_set_user_permissions(
  p_user_id uuid,
  p_changes jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  change_item jsonb;
  key_value text;
  allowed_value boolean;
  old_value boolean;
BEGIN
  IF NOT public.mindup_is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Admin only';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE id = p_user_id) THEN
    RAISE EXCEPTION 'User not found';
  END IF;
  IF jsonb_typeof(p_changes) <> 'array' THEN
    RAISE EXCEPTION 'p_changes must be a JSON array';
  END IF;

  FOR change_item IN SELECT value FROM jsonb_array_elements(p_changes)
  LOOP
    key_value := change_item->>'permission_key';
    IF NOT EXISTS (
      SELECT 1 FROM public.app_permissions
      WHERE permission_key = key_value AND is_assignable = true
    ) THEN
      RAISE EXCEPTION 'Unknown or non-assignable permission: %', key_value;
    END IF;

    SELECT allowed INTO old_value
    FROM public.user_permission_overrides
    WHERE user_id = p_user_id AND permission_key = key_value;

    IF change_item->'allowed' IS NULL OR change_item->>'allowed' IS NULL THEN
      DELETE FROM public.user_permission_overrides
      WHERE user_id = p_user_id AND permission_key = key_value;
      allowed_value := NULL;
    ELSE
      allowed_value := (change_item->>'allowed')::boolean;
      INSERT INTO public.user_permission_overrides(user_id, permission_key, allowed, updated_by, updated_at)
      VALUES (p_user_id, key_value, allowed_value, auth.uid(), now())
      ON CONFLICT (user_id, permission_key) DO UPDATE SET
        allowed = EXCLUDED.allowed,
        updated_by = EXCLUDED.updated_by,
        updated_at = now();
    END IF;

    INSERT INTO public.permission_change_log
      (target_user_id, permission_key, previous_value, new_value, changed_by)
    VALUES (p_user_id, key_value, old_value, allowed_value, auth.uid());
  END LOOP;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_permission(
  p_user_id uuid,
  p_permission_key text,
  p_allowed boolean DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  PERFORM public.admin_set_user_permissions(
    p_user_id,
    jsonb_build_array(jsonb_build_object('permission_key', p_permission_key, 'allowed', p_allowed))
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_get_permission_management()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result jsonb;
BEGIN
  IF NOT public.mindup_is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'Admin only';
  END IF;

  SELECT jsonb_build_object(
    'catalog', COALESCE((
      SELECT jsonb_agg(to_jsonb(p) ORDER BY p.sort_order, p.permission_key)
      FROM public.app_permissions p
      WHERE p.is_assignable = true
    ), '[]'::jsonb),
    'role_defaults', COALESCE((
      SELECT jsonb_object_agg(role_name, permissions)
      FROM (
        SELECT role_name, jsonb_object_agg(permission_key, allowed) AS permissions
        FROM public.role_permission_defaults
        GROUP BY role_name
      ) role_rows
    ), '{}'::jsonb),
    'users', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'id', u.id, 'full_name', u.full_name, 'email', u.email, 'role', u.role::text,
          'overrides', COALESCE((
            SELECT jsonb_object_agg(o.permission_key, o.allowed)
            FROM public.user_permission_overrides o
            JOIN public.app_permissions p ON p.permission_key = o.permission_key
            WHERE o.user_id = u.id AND p.is_assignable = true
          ), '{}'::jsonb)
        ) ORDER BY u.full_name NULLS LAST, u.email
      )
      FROM public.users u
      WHERE u.role::text IN ('admin', 'teacher', 'assistant')
    ), '[]'::jsonb)
  ) INTO result;
  RETURN result;
END;
$$;

-- Detailed tuition write gate. Existing ownership policies remain in force.
DO $$
BEGIN
  IF to_regclass('public.courses') IS NOT NULL THEN
    DROP POLICY IF EXISTS app_permission_courses_delete ON public.courses;
    CREATE POLICY app_permission_courses_delete ON public.courses
      AS RESTRICTIVE FOR DELETE TO authenticated
      USING (public.has_app_permission('courses.delete'));
  END IF;
  IF to_regclass('public.classes') IS NOT NULL THEN
    DROP POLICY IF EXISTS app_permission_classes_delete ON public.classes;
    CREATE POLICY app_permission_classes_delete ON public.classes
      AS RESTRICTIVE FOR DELETE TO authenticated
      USING (public.has_app_permission('classes.delete'));
  END IF;
  IF to_regclass('public.reference_materials') IS NOT NULL THEN
    DROP POLICY IF EXISTS app_permission_reference_materials_insert ON public.reference_materials;
    DROP POLICY IF EXISTS app_permission_reference_materials_update ON public.reference_materials;
    DROP POLICY IF EXISTS app_permission_reference_materials_delete ON public.reference_materials;
    CREATE POLICY app_permission_reference_materials_insert ON public.reference_materials
      AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (public.has_app_permission('resources.manage'));
    CREATE POLICY app_permission_reference_materials_update ON public.reference_materials
      AS RESTRICTIVE FOR UPDATE TO authenticated
      USING (public.has_app_permission('resources.manage'))
      WITH CHECK (public.has_app_permission('resources.manage'));
    CREATE POLICY app_permission_reference_materials_delete ON public.reference_materials
      AS RESTRICTIVE FOR DELETE TO authenticated USING (public.has_app_permission('resources.manage'));
  END IF;
  IF to_regclass('public.trial_lesson_requests') IS NOT NULL THEN
    DROP POLICY IF EXISTS app_permission_trial_requests_insert ON public.trial_lesson_requests;
    DROP POLICY IF EXISTS app_permission_trial_requests_update ON public.trial_lesson_requests;
    DROP POLICY IF EXISTS app_permission_trial_requests_delete ON public.trial_lesson_requests;
    CREATE POLICY app_permission_trial_requests_insert ON public.trial_lesson_requests
      AS RESTRICTIVE FOR INSERT TO authenticated WITH CHECK (public.has_app_permission('trial.manage'));
    CREATE POLICY app_permission_trial_requests_update ON public.trial_lesson_requests
      AS RESTRICTIVE FOR UPDATE TO authenticated
      USING (public.has_app_permission('trial.manage'))
      WITH CHECK (public.has_app_permission('trial.manage'));
    CREATE POLICY app_permission_trial_requests_delete ON public.trial_lesson_requests
      AS RESTRICTIVE FOR DELETE TO authenticated USING (public.has_app_permission('trial.manage'));
  END IF;
  IF to_regclass('public.tuition_payments') IS NOT NULL THEN
    DROP POLICY IF EXISTS app_permission_tuition_payments_insert ON public.tuition_payments;
    DROP POLICY IF EXISTS app_permission_tuition_payments_update ON public.tuition_payments;
    DROP POLICY IF EXISTS app_permission_tuition_payments_delete ON public.tuition_payments;
    CREATE POLICY app_permission_tuition_payments_insert ON public.tuition_payments
      AS RESTRICTIVE FOR INSERT TO authenticated
      WITH CHECK (
        public.has_app_permission('tuition.collect') OR
        public.has_app_permission('tuition.notes.manage') OR
        public.has_app_permission('tuition.surplus.manage') OR
        public.has_app_permission('tuition.refund') OR
        public.has_app_permission('tuition.lock')
      );
    CREATE POLICY app_permission_tuition_payments_update ON public.tuition_payments
      AS RESTRICTIVE FOR UPDATE TO authenticated
      USING (
        public.has_app_permission('tuition.collect') OR
        public.has_app_permission('tuition.notes.manage') OR
        public.has_app_permission('tuition.surplus.manage') OR
        public.has_app_permission('tuition.refund') OR
        public.has_app_permission('tuition.lock')
      )
      WITH CHECK (
        public.has_app_permission('tuition.collect') OR
        public.has_app_permission('tuition.notes.manage') OR
        public.has_app_permission('tuition.surplus.manage') OR
        public.has_app_permission('tuition.refund') OR
        public.has_app_permission('tuition.lock')
      );
    CREATE POLICY app_permission_tuition_payments_delete ON public.tuition_payments
      AS RESTRICTIVE FOR DELETE TO authenticated
      USING (public.has_app_permission('tuition.refund'));
    DROP POLICY IF EXISTS app_permission_tuition_payments_select ON public.tuition_payments;
    CREATE POLICY app_permission_tuition_payments_select ON public.tuition_payments
      AS RESTRICTIVE FOR SELECT TO authenticated
      USING (
        public.mindup_is_admin(auth.uid())
        OR public.has_app_permission('tuition.view_all')
        OR student_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM public.parent_students ps
          WHERE ps.parent_id = auth.uid()
            AND ps.student_id = tuition_payments.student_id
            AND ps.revoked_at IS NULL
        )
        OR (
          public.has_app_permission('tuition.view_assigned')
          AND EXISTS (
            SELECT 1
            FROM public.class_students cs
            JOIN public.class_teachers ct ON ct.class_id = cs.class_id
            WHERE cs.student_id = tuition_payments.student_id
              AND ct.teacher_id = auth.uid()
              AND (cs.left_at IS NULL OR cs.left_at >= tuition_payments.month)
          )
        )
      );
  END IF;
END $$;

ALTER TABLE public.permission_change_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS permission_change_log_admin_read ON public.permission_change_log;
CREATE POLICY permission_change_log_admin_read ON public.permission_change_log
FOR SELECT TO authenticated USING (public.mindup_is_admin(auth.uid()));

REVOKE ALL ON FUNCTION public.admin_set_user_permissions(uuid, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_set_user_permissions(uuid, jsonb) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_set_user_permission(uuid, text, boolean) TO authenticated, service_role;
GRANT SELECT ON public.permission_change_log TO authenticated;
